{{ if and .Values.global.mongodb.enabled .Values.global.mongodb.logicalBackup.enabled }}
{{- $backup := .Values.global.mongodb.logicalBackup }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-backup" .Values.global.mongodb.clusterName }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  schedule: {{ $backup.schedule | default "45 03 * * *" }}
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
        {{- if $backup.annotations }}
          annotations:
            {{- toYaml $backup.annotations | nindent 12 }}
        {{- end }}
        {{- if $backup.labels }}
          labels:
            {{- toYaml $backup.labels | nindent 12 }}
        {{- end }}
        spec:
          containers:
            - name: mongodb-backup
              image: ghcr.io/obmondo/mongodb-backup:latest
              imagePullPolicy: IfNotPresent
              env:
                # The MongoDB URI to access the database.
                # E.g.
                # Standalone instance   "mongodb://user:pass@host:port/dbname"
                # ReplicaSet            "mongodb://user:pass@mongo-rs0.svc:27017?replicaSet=mongo-rs&ssl=false"
                - name: MONGO_URI
                  valueFrom:
                    secretKeyRef:
                      name: mongodbbackup
                      key: MONGO_URI
                # Setting this to true will take a backup of all the databases
                - name: MONGO_COMPLETE
                  valueFrom:
                    secretKeyRef:
                      name: mongodbbackup
                      key: MONGO_COMPLETE
                - name: BACKUP_PROVIDER
                  value: {{ $backup.provider | default "az" }}
              {{- if eq $backup.provider "s3" }}
                - name: S3_BUCKET
                  value: {{ $backup.s3bucket }}
                - name: S3_PATH
                  value: {{ $backup.s3backuppath }}
              {{- if not $backup.useiamrole }}
                - name: BACKUP_S3_REGION
                  value: {{ $backup.s3region | default "us-east-1" }}
                - name: BACKUP_S3_ENDPOINT
                  value: {{ $backup.s3endpoint }}
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: awsaccesskeyid
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: mongodbbackup
                      key: AWS_SECRET_ACCESS_KEY
              {{- end }}
              {{- else if eq $backup.provider "az" }}
                - name: AZ_BACKUP_PATH
                  value:  {{ $backup.azbackuppath | default "mongodb-backup/graylog-mongodb" }}
                - name: AZURE_STORAGE_ACCOUNT_NAME
                  valueFrom:
                    secretKeyRef:
                      name: mongodbbackup
                      key: AZURE_STORAGE_ACCOUNT_NAME
                # Azure accountkey
                - name: AZURE_STORAGE_ACCOUNT_KEY
                  valueFrom:
                    secretKeyRef:
                      name: mongodbbackup
                      key: AZURE_STORAGE_ACCOUNT_KEY
                # Azure container namemongodbbackup
                - name: AZURE_STORAGE_CONTAINER
                  valueFrom:
                    secretKeyRef:
                      name: mongodbbackup
                      key: AZURE_STORAGE_CONTAINER
              {{- end }}
              resources:
                limits:
                  cpu: 100m
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 256Mi
              securityContext:
                privileged: false
                readOnlyRootFilesystem: false
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          terminationGracePeriodSeconds: 300
---
{{ end }}
