{{ if .Values.global.mongodb.enabled }}
{{- $mongodb := .Values.global.mongodb }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $mongodb.clusterName }}
  namespace: {{ .Release.Namespace }}
---
{{ end }}