apiVersion: v1
name: mattermost-team-edition
version: 6.6.6
dependencies:
  - name: mattermost-team-edition
    version: 6.6.96
    repository: https://helm.mattermost.com
  - name: kubeaid-addons
    version: 0.1.0
    repository: file://../kubeaid-addons
