global:
  netpol:
    enabled: false
  mattermost-team-edition:
    netpol: false

  postgresql:
    enabled: true
    instanceName: mattermost-team-edition
    instances: 1
    monitoring:
      enablePodMonitor: true
    size: 8Gi
    recover:
      enabled: false
    backups:
      enabled: false
      schedule: "0 2 * * *"
      retentionPolicy: 30d
      provider: aws
      aws:
        enableKube2IAMIntegration: true
    logicalbackup:
      enabled: false
      schedule: "0 2 * * *"
      provider: s3
      retention: "30d"
    resources:
      limits:
        memory: 800Mi
        cpu: 250m
      requests:
        memory: 500Mi
        cpu: 250m

mattermost-team-edition:
  revisionHistoryLimit: 0
  mysql:
    enabled: false
  externalDB:
    enabled: true
  extraEnvVars:
  - name: MM_DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: mattermost-pgsql-app
        key: username
  - name: MM_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mattermost-pgsql-app
        key: password
  - name: MM_SQLSETTINGS_DATASOURCE
    value: postgres://$(MM_DB_USERNAME):$(MM_DB_PASSWORD)@mattermost-pgsql-rw:5432/mattermost?sslmode=require&connect_timeout=100
  - name: MM_GITLABSETTINGS_ID
    valueFrom:
      secretKeyRef:
        name: mattermost-team-config
        key: gitlabsettings-id
  - name: MM_GITLABSETTINGS_SECRET
    valueFrom:
      secretKeyRef:
        name: mattermost-team-config
        key: gitlabsettings-secret
  config:
    MM_SQLSETTINGS_DRIVERNAME: "postgres"
    POSTGRES_DB_NAME_MATTERMOST: "mattermost"
    MM_TEAMSETTINGS_ENABLEUSERCREATION: "true"
    MM_GITLABSETTINGS_ENABLE: "true"
    MM_FILESETTINGS_DIRECTORY: "/mattermost/data/"
    MM_PLUGINSETTINGS_ENABLEUPLOADS: "true"
  # For fixing the permissions of the mattermost directory
  securityContext:
    runAsUser: 2000
    runAsGroup: 2000
    fsGroup: 2000
  # For fixing premature crashloopbackoff error
  startupProbe:
    initialDelaySeconds: 100
  livenessProbe:
    initialDelaySeconds: 10
  readinessProbe:
    initialDelaySeconds: 150
