{{- if and .Values.global.postgresql.enabled .Values.global.postgresql.backups.enabled }}
{{- $backups := .Values.global.postgresql.backups }}

apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: {{ .Values.global.postgresql.instanceName }}-pgsql-backups

spec:
  configuration:
    {{- if $backups.endpointURL }}
    endpointURL: {{ $backups.endpointURL }}
    {{- end }}
    {{- if $backups.destinationPath }}
    destinationPath: {{ required ".postgresql.backups.destinationPath must be provided" $backups.destinationPath }}
    {{- end }}
    {{- if or (eq ($backups.cloud | default "") "aws") (eq ($backups.provider | default "") "aws") }}
    s3Credentials:
      {{- if $backups.aws.enableKube2IAMIntegration }}
      inheritFromIAMRole: true
      {{- else }}
      accessKeyId:
        name: {{ .Values.global.postgresql.instanceName }}-pgsql-backup-creds
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: {{ .Values.global.postgresql.instanceName }}-pgsql-backup-creds
        key: ACCESS_SECRET_KEY
      {{- end }}
    {{- end }}

    wal:
      compression: gzip
      encryption: AES256
      maxParallel: 8

  retentionPolicy: {{ $backups.retentionPolicy }}
{{- end }}
