{{- if and ((.Values.global).netpol).enabled ((.Values.global).postgresql).netpol ((.Values.global).postgresql).logicalbackup ((.Values.global).postgresql.logicalbackup).enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: postgresql-backup-networkpolicy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: cilium-networkpolicy
spec:
  endpointSelector:
    matchLabels:
      app: {{ .Values.global.postgresql.instanceName }}-logical-backup 

  egress:
    # PostgreSQL (pg_dump)
    - toServices:
      - k8sService:
          serviceName: {{ .Values.global.postgresql.instanceName | default "postgresql" }}-pgsql-rw
          namespace: {{ .Release.Namespace }}
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP

    {{- if eq .Values.global.postgresql.logicalbackup.provider "az" }}
    # Azure Blob Storage
    - toFQDNs:
        - matchPattern: "*.blob.core.windows.net"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    {{- else if eq .Values.global.postgresql.logicalbackup.provider "s3" }}
    # S3 object storage
    {{- if .Values.global.postgresql.logicalbackup.s3endpoint }}
    - toFQDNs:
        - matchName: {{ .Values.global.postgresql.logicalbackup.s3endpoint | trimPrefix "https://" | trimPrefix "http://" | quote }}
        - matchPattern: "*.amazonaws.com"
        - matchPattern: "*.s3.amazonaws.com"
        - matchPattern: "*.s3.*.amazonaws.com"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    {{- else }}
    - toFQDNs:
        - matchPattern: "*.amazonaws.com"
        - matchPattern: "*.s3.amazonaws.com"
        - matchPattern: "*.s3.*.amazonaws.com"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    {{- end }}
    {{- end }}
{{- end }}
